### ISSUE TITLE
Aufzählung

### ISSUE THREAD

**Issue by RMeckler** [VincentSchreck/Dokumentation_Studienarbeit#10]
Aufzählung nur in dritte "dimension?" möglich.
Sprich es gibt kein subsubsubsection, was wir aber benötigen würden.

**Comment by VincentSchreck** [comment]
Man könnte \paragraph{} dazu umbauen:
Zuerst brauchst du das Package \usepackage{titlesec}

Bevor du \paragraph{} verwendest, musst du folgendes einfügen:
\setcounter{secnumdepth}{4}
\titleformat{\paragraph}{\normalfont\normalsize\bfseries}{\theparagraph}{1em}{}
\titlespacing*{\paragraph}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}

Und jetzt kannst du \paragraph{} statt \subsubsubsection{} benutzen.

ABER:
Es gibt einen Grund warum es eigentlich keine \subsubsubsection{} gibt. Zu viel Strukturierung ist nicht gut. Man verliert sich beim lesen in den Unterkapiteln und es wird wesentlich unübersichtlicher. Auch \subsubsection sollte man nicht zu häufig verwenden. Sowas hätten wir eigentlich in "Wissenschaftliches Schreiben" lernen sollen.
Je nachdem kann man stattdessen Absätze mit dickgedruckten Überschriften drin oder drüber oder mit itemize eine Auflistung erstellen. Verwende das mit \paragraph{} bitte nur wenn es wirklich keine andere Möglichkeit gibt.
